# site settings
title: Still in development
subtitle: By Tahsin Tariq
email: tahsinbanna@gmail.com
description: Stuff by Tahsin
baseurl: "" # the subpath of your site, e.g. /blog
url: 
author: Tahsin Tariq
street_address: 27
city: Dhanmondi
state: Dhaka
zip_code: 
country: Bangladesh
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6


# social settings
500px_url:
facebook_url:
github_url: https://github.com/TahsinTariq
instagram_url: https://instagram.com
linkedin_url: https://www.instagram.com/tahsintariqbanna/
pinterest_url:
slack_url:

# build settings
markdown: kramdown

sass:
  style: compressed
