# site settings
title: Still in development
subtitle: By Tahsin Tariq
email: tahsinbanna@gmail.com
description: Stuff by Tahsin
baseurl: "" # the subpath of your site, e.g. /blog
url: 
author: Tahsin Tariq
street_address: Road - 27, Dhanmondi
city: Dhaka
state: 
zip_code: 
country: Bangladesh
phone: +8801521443393

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 10


# social settings
500px_url:
facebook_url:
github_url: https://github.com/TahsinTariq
instagram_url: https://www.instagram.com/tahsintariqbanna/
linkedin_url: 
pinterest_url:
slack_url:
openprocessing_url: https://www.openprocessing.org/user/230948/

# build settings
markdown: kramdown

sass:
  style: compressed
